"""add_password_and_phone_to_users

Revision ID: 35515012fc21
Revises: 9a53f8f2f9f6
Create Date: 2026-06-06 18:44:15.349808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '35515012fc21'
down_revision: Union[str, None] = '9a53f8f2f9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
