"""add_password_and_phone_to_users

Revision ID: 9a53f8f2f9f6
Revises: 0001
Create Date: 2026-06-06 18:38:22.174208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a53f8f2f9f6'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('acts_act_id_key', 'acts', type_='unique')
    op.drop_index('idx_acts_act_id', table_name='acts')
    op.drop_index('idx_acts_category', table_name='acts')
    op.drop_index('idx_acts_embedding', table_name='acts', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_acts_act_id'), 'acts', ['act_id'], unique=True)
    op.create_index(op.f('ix_acts_category'), 'acts', ['category'], unique=False)
    op.drop_index('idx_cases_embedding', table_name='cases', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_index('idx_messages_session_id', table_name='messages')
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.drop_index('idx_sections_act_id', table_name='sections')
    op.drop_index('idx_sections_embedding', table_name='sections', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_sections_act_id'), 'sections', ['act_id'], unique=False)
    op.add_column('users', sa.Column('hashed_password', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'phone')
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_sections_act_id'), table_name='sections')
    op.create_index('idx_sections_embedding', 'sections', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_sections_act_id', 'sections', ['act_id'], unique=False)
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.create_index('idx_messages_session_id', 'messages', ['session_id'], unique=False)
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('idx_cases_embedding', 'cases', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_acts_category'), table_name='acts')
    op.drop_index(op.f('ix_acts_act_id'), table_name='acts')
    op.create_index('idx_acts_embedding', 'acts', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_acts_category', 'acts', ['category'], unique=False)
    op.create_index('idx_acts_act_id', 'acts', ['act_id'], unique=False)
    op.create_unique_constraint('acts_act_id_key', 'acts', ['act_id'])
    # ### end Alembic commands ###
